In [1]:
#import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix

import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import SnowballStemmer
import re


In [2]:
#import data
spam_df = pd.read_csv("D:\\Datasets\\spam.csv")
spam_df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
#inspact data
spam_df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [4]:
#turning spam/ham into numerical data, creating new column called 'spam'
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x == 'spam'else 0)
#x=spam_df.Message
y=spam_df.spam


In [5]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [6]:
ps = PorterStemmer()
def clean_text(text):
    # Remove any unwanted characters
    text = re.sub(r"[^A-Za-z0-9]", " ", text)
    # Convert to lowercase
    text = text.lower()
    # Remove stopwords and stem the words
    words = [ps.stem(word) for word in text.split() if word not in stopwords.words("english")]
    return " ".join(words)

# Apply the clean_text function to the text column of the DataFrame
spam_df["Message"] = spam_df["Message"].apply(clean_text)

In [42]:
x=spam_df.Message
spam_df

Category                                            Message  spam
0         ham  go jurong point crazi avail bugi n great world...     0
1         ham                              ok lar joke wif u oni     0
2        spam  free entri 2 wkli comp win fa cup final tkt 21...     1
3         ham                u dun say earli hor u c alreadi say     0
4         ham               nah think goe usf live around though     0
...       ...                                                ...   ...
5567     spam  2nd time tri 2 contact u u 750 pound prize 2 c...     1
5568      ham                              b go esplanad fr home     0
5569      ham                                  piti mood suggest     0
5570      ham  guy bitch act like interest buy someth els nex...     0
5571      ham                                     rofl true name     0

[5572 rows x 3 columns]

In [8]:
#find the word count and store data as a matrix
cv = CountVectorizer()
x_count = cv.fit_transform(x) 

In [9]:
#create train/test split
x_train_1 ,x_test_1 , y_train , y_test = train_test_split(x_count, y,test_size=0.3,random_state=42)

In [10]:
#train model 
model1_m = MultinomialNB()
model1_m.fit(x_train_1,y_train)

MultinomialNB()

In [11]:
from sklearn.naive_bayes import GaussianNB
X_gs = x_count.toarray()
x_train_1_G, x_test_1_G, y_train, y_test = train_test_split(X_gs, y, test_size=0.3,random_state=42)
model1_G = GaussianNB()
model1_G.fit(x_train_1_G,y_train)

GaussianNB()

In [12]:
from sklearn.naive_bayes import BernoulliNB

model1_B = BernoulliNB()
model1_B.fit(x_train_1,y_train)

BernoulliNB()

In [13]:
from sklearn.metrics import confusion_matrix
y_pred_m= model1_m.predict(x_test_1)
accuracy = accuracy_score(y_test, y_pred_m)
precision = precision_score(y_test, y_pred_m)
recall = recall_score(y_test, y_pred_m)
f1 = f1_score(y_test, y_pred_m)
print(f"MultinomialNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_m)
confusion_matrics

MultinomialNB :Accuracy: 0.9826555023923444, Precision: 0.922077922077922, Recall: 0.9508928571428571, F1-score: 0.9362637362637363


array([[1430,   18],
       [  11,  213]], dtype=int64)

In [14]:

y_pred_G= model1_G.predict(x_test_1_G)
accuracy = accuracy_score(y_test, y_pred_G)
precision = precision_score(y_test, y_pred_G)
recall = recall_score(y_test, y_pred_G)
f1 = f1_score(y_test, y_pred_G)
print(f"GaussianNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_G)
confusion_matrics

GaussianNB :Accuracy: 0.8755980861244019, Precision: 0.520618556701031, Recall: 0.9017857142857143, F1-score: 0.6601307189542485


array([[1262,  186],
       [  22,  202]], dtype=int64)

In [15]:
y_pred_B= model1_B.predict(x_test_1)
accuracy = accuracy_score(y_test, y_pred_B)
precision = precision_score(y_test, y_pred_B)
recall = recall_score(y_test, y_pred_B)
f1 = f1_score(y_test, y_pred_B)
print(f"BernoulliNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_B)
confusion_matrics

BernoulliNB :Accuracy: 0.9754784688995215, Precision: 0.9692307692307692, Recall: 0.84375, F1-score: 0.9021479713603818


array([[1442,    6],
       [  35,  189]], dtype=int64)

_____________________________________________________

In [81]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=True)
x_tf = tf_transformer.fit_transform(x_count)

# from sklearn.feature_extraction.text import TfidfVectorizer
# tfidf_c = TfidfVectorizer()
# x_tf = tfidf_c.fit_transform(x)

In [82]:
x_train2 ,x_test2 , y_train , y_test = train_test_split(x_tf, y,test_size=0.3,random_state=42)

In [83]:
#train model 
model2_m = MultinomialNB()
model2_m.fit(x_train2,y_train)

MultinomialNB()

In [84]:
X_tf_gs = x_tf.toarray()
x_train_2_G, x_test_2_G, y_train, y_test = train_test_split(X_tf_gs, y, test_size=0.3,random_state=42)
model2_G = GaussianNB()
model2_G.fit(x_train_2_G,y_train)

GaussianNB()

In [85]:
model2_B = BernoulliNB()
model2_B.fit(x_train2,y_train)

BernoulliNB()

### results :

In [86]:
y_pred_m= model2_m.predict(x_test2)
accuracy = accuracy_score(y_test, y_pred_m)
precision = precision_score(y_test, y_pred_m)
recall = recall_score(y_test, y_pred_m)
f1 = f1_score(y_test, y_pred_m)
print(f"MultinomialNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_m)
confusion_matrics

MultinomialNB :Accuracy: 0.9677033492822966, Precision: 1.0, Recall: 0.7589285714285714, F1-score: 0.8629441624365483


array([[1448,    0],
       [  54,  170]], dtype=int64)

In [87]:
y_pred_G= model2_G.predict(x_test_2_G)
accuracy = accuracy_score(y_test, y_pred_G)
precision = precision_score(y_test, y_pred_G)
recall = recall_score(y_test, y_pred_G)
f1 = f1_score(y_test, y_pred_G)
print(f"GaussianNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_G)
confusion_matrics

GaussianNB :Accuracy: 0.8755980861244019, Precision: 0.5210526315789473, Recall: 0.8839285714285714, F1-score: 0.6556291390728477


array([[1266,  182],
       [  26,  198]], dtype=int64)

In [66]:
y_pred_B= model2_B.predict(x_test2)
accuracy = accuracy_score(y_test, y_pred_B)
precision = precision_score(y_test, y_pred_B)
recall = recall_score(y_test, y_pred_B)
f1 = f1_score(y_test, y_pred_B)
print(f"BernoulliNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_B)
confusion_matrics

BernoulliNB :Accuracy: 0.9754784688995215, Precision: 0.9692307692307692, Recall: 0.84375, F1-score: 0.9021479713603818


array([[1442,    6],
       [  35,  189]], dtype=int64)

____________________________________________

In [92]:
# cv2 = CountVectorizer(binary=True)
# x_count2 = cv.fit_transform(x)
x_count2 = (x_count > 0).astype(int)
x_train3, x_test3, y_train, y_test = train_test_split(x_count2, y, test_size=0.3, random_state=42)
print(x_count2)

  (0, 1037)	1
  (0, 1224)	1
  (0, 1603)	1
  (0, 1605)	1
  (0, 1839)	1
  (0, 2049)	1
  (0, 3052)	1
  (0, 3092)	1
  (0, 3130)	1
  (0, 3721)	1
  (0, 3830)	1
  (0, 5028)	1
  (0, 6918)	1
  (0, 7095)	1
  (1, 3688)	1
  (1, 3861)	1
  (1, 4683)	1
  (1, 4708)	1
  (1, 7017)	1
  (2, 77)	1
  (2, 400)	1
  (2, 409)	1
  (2, 787)	1
  (2, 1109)	1
  (2, 1936)	1
  :	:
  (5567, 6461)	1
  (5567, 6586)	1
  (5568, 2585)	1
  (5568, 2874)	1
  (5568, 3052)	1
  (5568, 3346)	1
  (5569, 4356)	1
  (5569, 4970)	1
  (5569, 6172)	1
  (5570, 897)	1
  (5570, 1429)	1
  (5570, 1631)	1
  (5570, 2510)	1
  (5570, 2885)	1
  (5570, 2979)	1
  (5570, 3174)	1
  (5570, 3561)	1
  (5570, 3942)	1
  (5570, 4532)	1
  (5570, 5920)	1
  (5570, 6754)	1
  (5570, 6953)	1
  (5571, 4452)	1
  (5571, 5472)	1
  (5571, 6599)	1


In [53]:
model3_m = MultinomialNB()
model3_m.fit(x_train3,y_train)

MultinomialNB()

In [54]:
x_count2_g = x_count2.toarray()
x_train_3_G, x_test_3_G, y_train, y_test = train_test_split(x_count2_g, y, test_size=0.3,random_state=42)
model3_G = GaussianNB()
model3_G.fit(x_train_3_G,y_train)

GaussianNB()

In [55]:
model3_B = BernoulliNB()
model3_B.fit(x_train3,y_train)

BernoulliNB()

### Results:

In [56]:
y_pred_m= model3_m.predict(x_test3)
accuracy = accuracy_score(y_test, y_pred_m)
precision = precision_score(y_test, y_pred_m)
recall = recall_score(y_test, y_pred_m)
f1 = f1_score(y_test, y_pred_m)
print(f"MultinomialNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_m)
confusion_matrics

MultinomialNB :Accuracy: 0.9814593301435407, Precision: 0.9213973799126638, Recall: 0.9419642857142857, F1-score: 0.9315673289183223


array([[1430,   18],
       [  13,  211]], dtype=int64)

In [57]:
y_pred_G= model3_G.predict(x_test_3_G)
accuracy = accuracy_score(y_test, y_pred_G)
precision = precision_score(y_test, y_pred_G)
recall = recall_score(y_test, y_pred_G)
f1 = f1_score(y_test, y_pred_G)
print(f"GaussianNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_G)
confusion_matrics

GaussianNB :Accuracy: 0.8767942583732058, Precision: 0.5231958762886598, Recall: 0.90625, F1-score: 0.6633986928104576


array([[1263,  185],
       [  21,  203]], dtype=int64)

In [58]:
y_pred_B= model3_B.predict(x_test3)
accuracy = accuracy_score(y_test, y_pred_B)
precision = precision_score(y_test, y_pred_B)
recall = recall_score(y_test, y_pred_B)
f1 = f1_score(y_test, y_pred_B)
print(f"BernoulliNB :Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-score: {f1}")
confusion_matrics = confusion_matrix(y_test,y_pred_B)
confusion_matrics

BernoulliNB :Accuracy: 0.9754784688995215, Precision: 0.9692307692307692, Recall: 0.84375, F1-score: 0.9021479713603818


array([[1442,    6],
       [  35,  189]], dtype=int64)